feat: add new chart: monom-spring-job
ThingsO2/helm-charts pull request #12
Opened 2021-09-28 08:51 UTC by jilgue

2021-09-28 08:52 UTC, jilgue commented
Example:
```
# Source: monom-spring-job/templates/cronjob.yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: job
  labels:
    helm.sh/chart: monom-spring-job-1.0.0
    app.kubernetes.io/name: job
    app.kubernetes.io/version: "1.19.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: data-intake
    app.kubernetes.io/part-of: data-intake
    app.kubernetes.io/instance: job-randAlphaNum
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 0
  schedule: "* * * * *"
  successfulJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: job
        spec:
          securityContext:
            {}
          containers:
            - name: job
              securityContext:
                {}
              image: hello-world:linux
              imagePullPolicy: IfNotPresent
              env:
                - name: SPRING_PROFILES_ACTIVE
                  value: dev
                - name: SPRING_CONFIG_URI
                  value: http://spring-config-server:8888
                - name: MONGODB_SRV_CONNECTION
                  valueFrom:
                    secretKeyRef:
                      key: srv
                      name: mongodb-connection-string
              resources:
                limits:
                  cpu: 75m
                  memory: 51Mi
                requests:
                  cpu: 25m
                  memory: 51Mi
          restartPolicy: Never
```

2021-09-29 14:46 UTC, acortesma requested changes

2021-09-29 14:46 UTC, acortesma commented on charts/monom-spring-job/values.yaml
> +    memory: 512Mi
Cambia estos recursos por defecto por
```yaml
resources:
  limits:
    cpu: 500m
    memory: 500Mi
  requests:
    cpu: 50m
    memory: 350Mi
```

2021-09-30 05:54 UTC, jilgue commented on charts/monom-spring-job/values.yaml
> +    memory: 512Mi
Hecho !

2021-09-30 05:57 UTC, merged